spring:
  application:
    name: dddlibrary
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library?useSSL=false
    username: flavius
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  flyway:
    clean-disabled: false
    baseline-on-migrate: true
server:
  port: 9111
